"""add_supabase_and_folders

Revision ID: a34c0e716910
Revises: 1d7de949a987
Create Date: 2026-05-31 11:03:14.537941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34c0e716910'
down_revision: Union[str, None] = '1d7de949a987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_logs_event_id', table_name='webhook_logs')
    op.drop_index('ix_webhook_logs_order_id', table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index('idx_jobs_folder_id', table_name='jobs')
    op.drop_index('idx_jobs_workspace_id', table_name='jobs')
    op.create_index(op.f('ix_jobs_folder_id'), 'jobs', ['folder_id'], unique=False)
    op.create_index(op.f('ix_jobs_workspace_id'), 'jobs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_workspace_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_folder_id'), table_name='jobs')
    op.create_index('idx_jobs_workspace_id', 'jobs', ['workspace_id'], unique=False)
    op.create_index('idx_jobs_folder_id', 'jobs', ['folder_id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('event_id', name='webhook_logs_pkey')
    )
    op.create_index('ix_webhook_logs_order_id', 'webhook_logs', ['order_id'], unique=False)
    op.create_index('ix_webhook_logs_event_id', 'webhook_logs', ['event_id'], unique=False)
    # ### end Alembic commands ###
